service: transaction-service-api
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_KEY: ${env:SUPABASE_KEY}

plugins:
  - serverless-offline

functions:
  lambdaTransaction:
    name: lambdaTransaction-${opt:stage, 'dev'}
    handler: src/infrastructure/lambdas/handler.createTransactionHandler
    timeout: 90
    events:
      - http:
          path: /transactions
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false
  
  listTransactions:
    name: lambdaListTransactions-${opt:stage, 'dev'}
    handler: src/infrastructure/lambdas/handler.getAllTransactionsHandler
    events:
      - http:
          path: /transactions
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false

  getTransactionDetails:
    name: lambdaGetTransactionDetails-${opt:stage, 'dev'}
    handler: src/infrastructure/lambdas/handler.getTransactionDetailsHandler
    events:
      - http:
          path: /transactions/{id}
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false

  updateTransaction:
    name: lambdaUpdateTransaction-${opt:stage, 'dev'}
    handler: src/infrastructure/lambdas/handler.updateTransactionHandler
    events:
      - http:
          path: /transactions/{id}
          method: put
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false

  
  swaggerSpec:
    name: swaggerSpec-${opt:stage, 'dev'}
    handler: src/infrastructure/lambdas/swaggerHandler.handler
    events:
      - http:
          path: /swagger.json
          method: get
          cors: true
  
  swaggerUI:
    name: swaggerUI-${opt:stage, 'dev'}
    handler: src/infrastructure/lambdas/swaggerUIHandler.handler
    events:
      - http:
          path: /swagger-ui
          method: get
          cors: true
      - http:
          path: /swagger-ui/{proxy+}
          method: get
          cors: true

  
  