service: transaction-service-api
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_KEY: ${env:SUPABASE_KEY}

plugins:
  - serverless-offline

functions:
  lambdaTransaction:
    name: lambdaTransaction-${opt:stage, 'dev'}
    handler: src/infrastructure/lambdas/handler.createTransactionHandler
    events:
      - http:
          path: /transactions
          method: post
          cors: true
  
  getAllStatuses:
    name: getAllStatuses-${opt:stage, 'dev'}
    handler: src/infrastructure/lambdas/handler.getAllStatusesHandler
    events:
      - http:
          path: /transaction/status
          method: get
          cors: true
  
  getStatusById:
    name: getStatusById-${opt:stage, 'dev'}
    handler: src/infrastructure/lambdas/handler.getStatusByIdHandler
    events:
      - http:
          path: /transaction/status/{id}
          method: get
          cors: true
  